### ISSUE TITLE
Need to Have Labs Conform to Single Source of Truth Paradigm

### ISSUE THREAD

**Issue by MinesJA** [learn-co-curriculum/ruby-objects-has-many-lab#10]
We're currently teaching Single Source of Truth in lectures and asking students to only store references to other objects in one place (on the "Belongs To" instance) but in this lab are asking them to store them as an attribute of the belongs to instance and also in an array on the has many instance which violates SST principles.

I created a WIP branch on this lab which I'll submit as a PR. In it I changed tests, readmes, and working solution. I have students create global variables on all classes which store new instances on initialization and then have students create a method on the has-many class (Artists, for example) that looks for all the instances that belong to that instance in the class that belongs to it (Songs).

I also took out the global variable counters and have them create a method that looks for that count in the other class because I think its worth driving home the idea you can find info on a class from another class just by calling the first class (in the Artist class, Song.all.count, for example).

**Comment by DanielSeehausen** [comment]
thank you @MinesJA !
your PR addressed just this! It has been merged and the issue closed. 
Great thinking removing the counters as well.
