### ISSUE TITLE
Unfinished sentence in this lab

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/ruby-objects-has-many-lab#14]
This sentence ends in midair:
"To do this, you'll need to create a global variable that keeps track of all

Thank you.

Valerie

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
