### ISSUE TITLE
"global variable" and typo

### ISSUE THREAD

**Issue by micahshute** [learn-co-curriculum/ruby-objects-has-many-lab#15]
Hi, I noticed a couple of things in this lab - there are multiple times that it is instructed to create a "global variable" when I think the intent is to create class variables, not global variables. Also, in the "Who Knows About Who?" paragraph, it seems that the paragraph is unfinished - the last sentence stops halfway through. Thanks!

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
