### ISSUE TITLE
The tests do not check whether #add_song_by_name and #add_post_by_title respectively return the new song and post.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/ruby-objects-has-many-lab#17]
Hello. Despite the README stating that #add_song_by_name in the Artist class should return the new song, and that #add_post_by_title in the Author class should return the new Post, the tests do not check for that. 

Despite the fact that my #add_song_by_name method returns the songs array instead of the new song, and the fact that my #add_post_by_title method returns the posts array instead of the new post, the tests still pass. I have attached a couple of screenshots for clarity. 

I know that this definitely is not a big issue, especially since my solution is considerably different from the official solution to begin with. Even so, thanks for looking into this.

Sdcrouse

![has many objects lab screenshot 2](https://user-images.githubusercontent.com/38870640/45123691-93b34480-b11c-11e8-8529-c0cf80ec54f1.gif)

![has many objects lab screenshot 4](https://user-images.githubusercontent.com/38870640/45123727-b180a980-b11c-11e8-903f-44851ed2bd0b.gif)

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @Sdcrouse.

We have removed this from the readme, clarified this section and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
