### ISSUE TITLE
Confusing test output for the Artist and Author classes

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/ruby-objects-has-many-lab#18]
Hello. This last issue that I am raising with this lab is the same as Issue #44 that was raised here: https://github.com/learn-co-students/ruby-objects-has-many-lab-v-000/issues/44

Due to the placement of an "end" keyword in the rspec tests for the #name method in the Artist and Author classes, all of the tests following #name are included in the #describe block for #name, leading to output such as this (note that I have put the strange part of the output in bold):

1) Artist **#name #add_song_by_name** takes in an argument of a song name, creates a new song with it and associates the song and artist
     Failure/Error: adele.add_song_by_name("Rolling in the Deep")
     NoMethodError:
       undefined method `add_song_by_name' for #<Artist:0x000000014a0348 @name="Adele", @songs=[]>

Here is the test for #name in the Artist class:

describe "#name" do
      it "has an attr_accessor for name" do
        expect(adele.name).to eq("Adele")
    end

Here is the test for #name in the Author class:

describe "#name" do
      it "has an attr_accessor for name" do
        expect(betty.name).to eq("Betty")
    end

The reason that these tests even work is that the missing "end" keyword in question is the second "end" keyword from the bottom of both rspec tests. Moving that keyword to the end of the "describe #name" test should solve the problem with the confusing test output.

Thank you for looking into this.

Sdcrouse

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @Sdcrouse.

We have fixed these tests and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
